In [1]:
import pandas as pd

In [7]:
mydata=pd.read_csv('/home/ramyaveerphotos/kiran/Customerprofile.csv')

In [4]:
campdata=pd.read_csv('/home/ramyaveerphotos/kiran/campaign.csv')

In [15]:
mydata['id']=campdata['CUST_ID']

In [19]:
mydata.columns=['CUST_ID','first_name', 'last_name', 'Gender', 'Date_of_Birth', 'country',
       'Age', 'Address', 'Occupation', 'Marital.Status', 'Geography_id',
       'email', 'Contact_Number', 'Annual.Income', 'Own.Home', 'Own.Car',
       'Own.property', 'Created_date', 'Modified_date', 'Zone_id', 'Zone_Name',
       'Region_id', 'Region_Name', 'Country_Name', 'Policy_id_sk',
       'Premium_Amount', 'Product_Name', 'Claim_Amount', 'NumOfClaims',
       'Channel_sk', 'Channel_code', 'Married_Since', 'House_tenure',
       'NoOfHomes', 'NumOfCars']

In [22]:
merged=pd.merge(campdata,mydata,on='CUST_ID')

In [39]:
frame=merged[['MARSTA_C','Date_of_Birth', 'country', 'Age', 'Occupation',
       'Marital.Status','Annual.Income', 'Own.Home', 'Own.Car', 'Own.property', 'Created_date',
       'Modified_date', 'Zone_id', 'Zone_Name', 'Region_id', 'Region_Name',
       'Country_Name', 'Policy_id_sk', 'Premium_Amount', 'Product_Name',
       'Claim_Amount', 'NumOfClaims', 'Channel_sk', 'Channel_code',
       'Married_Since', 'House_tenure', 'NoOfHomes', 'NumOfCars']]

In [50]:
n=10
while(n<len(frame)):
    for chunk in range(round(len(frame)/n)):
        print(frame.iloc[0:chunk,:])
        n=n+10

Empty DataFrame
Columns: [MARSTA_C, Date_of_Birth, country, Age, Occupation, Marital.Status, Annual.Income, Own.Home, Own.Car, Own.property, Created_date, Modified_date, Zone_id, Zone_Name, Region_id, Region_Name, Country_Name, Policy_id_sk, Premium_Amount, Product_Name, Claim_Amount, NumOfClaims, Channel_sk, Channel_code, Married_Since, House_tenure, NoOfHomes, NumOfCars]
Index: []

[0 rows x 28 columns]
   MARSTA_C Date_of_Birth country  Age  Occupation Marital.Status  \
0         1    10/05/1969  Sweden   46  MANAGEMENT        Married

   Annual.Income  Own.Home  Own.Car  Own.property  ... Premium_Amount  \
0      634668.78         2        1             2  ...      1298606.6

     Product_Name Claim_Amount NumOfClaims Channel_sk Channel_code  \
0  UnitGain Super   1924525.36        4.41  Channel_6          DMI

  Married_Since House_tenure  NoOfHomes NumOfCars
0             2           21          2         2

[1 rows x 28 columns]
   MARSTA_C Date_of_Birth country  Age  Occupation Marital.Status  \
0         1    10/05/1969  Sweden   46  MANAGEMENT        Married
1         0    07/26/1972  Canada   43      OTHERS      Unmarried

   Annual.Income  Own.Home  Own.Car  Own.property  ... Premium_Amount  \
0      634668.78         2        1             2  ...     1298606.60
1     1812686.77         1        1             1  ...     5517797.85

             Product_Name Claim_Amount NumOfClaims  Channel_sk Channel_code  \
0          UnitGain Super   1924525.36        4.41   Channel_6          DMI
1  Marine Cargo Insurance   2243649.44        7.41  Channel_24          DMI

  Married_Since House_tenure  NoOfHomes NumOfCars
0             2           21          2         2
1            15            8          1         2

[2 rows x 28 columns]
   MARSTA_C Date_of_Birth country  Age     Occupation Marital.Status  \
0         1    10/05/1969  Sweden   46     MANAGEMENT        Married
1         0    07/26/1972  Canada   43         OTHERS      Unmarried
2         0    08/05/1985  Russia   30  CIVIL SERVICE      Unmarried

   Annual.Income  Own.Home  Own.Car  Own.property  ... Premium_Amount  \
0      634668.78         2        1             2  ...     1298606.60
1     1812686.77         1        1             1  ...     5517797.85
2     1566549.64         2        1             2  ...     4559105.45

                              Product_Name Claim_Amount NumOfClaims  \
0                           UnitGain Super   1924525.36        4.41
1                   Marine Cargo Insurance   2243649.44        7.41
2  Classic Annuity/Guaranteed Life Annuity    353072.93        5.13

   Channel_sk Channel_code Married_Since House_tenure  NoOfHomes NumOfCars
0   Channel_6          DMI             2           21          2         2
1  Channel_24          DMI            15            8          1         2
2   Channel_5          DMI            10           18          3         1

[3 rows x 28 columns]
   MARSTA_C Date_of_Birth country  Age     Occupation Marital.Status  \
0         1    10/05/1969  Sweden   46     MANAGEMENT        Married
1         0    07/26/1972  Canada   43         OTHERS      Unmarried
2         0    08/05/1985  Russia   30  CIVIL SERVICE      Unmarried
3         0    12/10/1980   China   35             IT      Unmarried

   Annual.Income  Own.Home  Own.Car  Own.property  ... Premium_Amount  \
0      634668.78         2        1             2  ...     1298606.60
1     1812686.77         1        1             1  ...     5517797.85
2     1566549.64         2        1             2  ...     4559105.45
3      696245.15         1        2             1  ...     2539548.42

                              Product_Name Claim_Amount NumOfClaims  \
0                           UnitGain Super   1924525.36        4.41
1                   Marine Cargo Insurance   2243649.44        7.41
2  Classic Annuity/Guaranteed Life Annuity    353072.93        5.13
3                                Unit Gain    988123.02        5.00

   Channel_sk Channel_code Married_Since House_tenure  NoOfHomes NumOfCars
0   Channel_6          DMI             2           21          2         2
1  Channel_24          DMI            15            8          1         2
2   Channel_5          DMI            10           18          3         1
3  Channel_22           SM             4           21          3         3

[4 rows x 28 columns]
   MARSTA_C Date_of_Birth     country  Age     Occupation Marital.Status  \
0         1    10/05/1969      Sweden   46     MANAGEMENT        Married
1         0    07/26/1972      Canada   43         OTHERS      Unmarried
2         0    08/05/1985      Russia   30  CIVIL SERVICE      Unmarried
3         0    12/10/1980       China   35             IT      Unmarried
4         1    12/12/1979  Kazakhstan   36     MANAGEMENT      Unmarried

   Annual.Income  Own.Home  Own.Car  Own.property  ... Premium_Amount  \
0      634668.78         2        1             2  ...     1298606.60
1     1812686.77         1        1             1  ...     5517797.85
2     1566549.64         2        1             2  ...     4559105.45
3      696245.15         1        2             1  ...     2539548.42
4     1324025.64         2        2             1  ...     4337399.11

                              Product_Name Claim_Amount NumOfClaims  \
0                           UnitGain Super   1924525.36        4.41
1                   Marine Cargo Insurance   2243649.44        7.41
2  Classic Annuity/Guaranteed Life Annuity    353072.93        5.13
3                                Unit Gain    988123.02        5.00
4                    Enhanced Incomeshield          NaN         NaN

   Channel_sk Channel_code Married_Since House_tenure  NoOfHomes NumOfCars
0   Channel_6          DMI             2           21          2         2
1  Channel_24          DMI            15            8          1         2
2   Channel_5          DMI            10           18          3         1
3  Channel_22           SM             4           21          3         3
4  Channel_16         BANC             2            3          1         2

[5 rows x 28 columns]
   MARSTA_C Date_of_Birth     country  Age     Occupation Marital.Status  \
0         1    10/05/1969      Sweden   46     MANAGEMENT        Married
1         0    07/26/1972      Canada   43         OTHERS      Unmarried
2         0    08/05/1985      Russia   30  CIVIL SERVICE      Unmarried
3         0    12/10/1980       China   35             IT      Unmarried
4         1    12/12/1979  Kazakhstan   36     MANAGEMENT      Unmarried
5         0    10/27/1972   Indonesia   43         DOCTOR      Unmarried

   Annual.Income  Own.Home  Own.Car  Own.property  ... Premium_Amount  \
0      634668.78         2        1             2  ...     1298606.60
1     1812686.77         1        1             1  ...     5517797.85
2     1566549.64         2        1             2  ...     4559105.45
3      696245.15         1        2             1  ...     2539548.42
4     1324025.64         2        2             1  ...     4337399.11
5      801929.58         2        1             2  ...     2641898.18

                              Product_Name Claim_Amount NumOfClaims  \
0                           UnitGain Super   1924525.36        4.41
1                   Marine Cargo Insurance   2243649.44        7.41
2  Classic Annuity/Guaranteed Life Annuity    353072.93        5.13
3                                Unit Gain    988123.02        5.00
4                    Enhanced Incomeshield          NaN         NaN
5                              PrimeShield   1348617.54        1.18

   Channel_sk Channel_code Married_Since House_tenure  NoOfHomes NumOfCars
0   Channel_6          DMI             2           21          2         2
1  Channel_24          DMI            15            8          1         2
2   Channel_5          DMI            10           18          3         1
3  Channel_22           SM             4           21          3         3
4  Channel_16         BANC             2            3          1         2
5   Channel_8         CELL            14           16          0         2

[6 rows x 28 columns]

   MARSTA_C Date_of_Birth     country  Age     Occupation Marital.Status  \
0         1    10/05/1969      Sweden   46     MANAGEMENT        Married
1         0    07/26/1972      Canada   43         OTHERS      Unmarried
2         0    08/05/1985      Russia   30  CIVIL SERVICE      Unmarried
3         0    12/10/1980       China   35             IT      Unmarried
4         1    12/12/1979  Kazakhstan   36     MANAGEMENT      Unmarried
5         0    10/27/1972   Indonesia   43         DOCTOR      Unmarried
6         1    06/24/1971   Indonesia   44         WORKER      Unmarried

   Annual.Income  Own.Home  Own.Car  Own.property  ... Premium_Amount  \
0      634668.78         2        1             2  ...     1298606.60
1     1812686.77         1        1             1  ...     5517797.85
2     1566549.64         2        1             2  ...     4559105.45
3      696245.15         1        2             1  ...     2539548.42
4     1324025.64         2        2             1  ...     4337399.11
5      801929.58         2        1             2  ...     2641898.18
6      401932.36         1        2             1  ...     3453549.28

                              Product_Name Claim_Amount NumOfClaims  \
0                           UnitGain Super   1924525.36        4.41
1                   Marine Cargo Insurance   2243649.44        7.41
2  Classic Annuity/Guaranteed Life Annuity    353072.93        5.13
3                                Unit Gain    988123.02        5.00
4                    Enhanced Incomeshield          NaN         NaN
5                              PrimeShield   1348617.54        1.18
6                               FamilyGain   1846592.95        3.71

   Channel_sk Channel_code Married_Since House_tenure  NoOfHomes NumOfCars
0   Channel_6          DMI             2           21          2         2
1  Channel_24          DMI            15            8          1         2
2   Channel_5          DMI            10           18          3         1
3  Channel_22           SM             4           21          3         3
4  Channel_16         BANC             2            3          1         2
5   Channel_8         CELL            14           16          0         2
6  Channel_21         BANK            10           10          2         1

[7 rows x 28 columns]
   MARSTA_C Date_of_Birth     country  Age     Occupation Marital.Status  \
0         1    10/05/1969      Sweden   46     MANAGEMENT        Married
1         0    07/26/1972      Canada   43         OTHERS      Unmarried
2         0    08/05/1985      Russia   30  CIVIL SERVICE      Unmarried
3         0    12/10/1980       China   35             IT      Unmarried
4         1    12/12/1979  Kazakhstan   36     MANAGEMENT      Unmarried
5         0    10/27/1972   Indonesia   43         DOCTOR      Unmarried
6         1    06/24/1971   Indonesia   44         WORKER      Unmarried
7         1    03/06/1983       China   32         OTHERS        Married

   Annual.Income  Own.Home  Own.Car  Own.property  ... Premium_Amount  \
0      634668.78         2        1             2  ...     1298606.60
1     1812686.77         1        1             1  ...     5517797.85
2     1566549.64         2        1             2  ...     4559105.45
3      696245.15         1        2             1  ...     2539548.42
4     1324025.64         2        2             1  ...     4337399.11
5      801929.58         2        1             2  ...     2641898.18
6      401932.36         1        2             1  ...     3453549.28
7      627567.34         2        1             1  ...     1839349.40

                              Product_Name Claim_Amount NumOfClaims  \
0                           UnitGain Super   1924525.36        4.41
1                   Marine Cargo Insurance   2243649.44        7.41
2  Classic Annuity/Guaranteed Life Annuity    353072.93        5.13
3                                Unit Gain    988123.02        5.00
4                    Enhanced Incomeshield          NaN         NaN
5                              PrimeShield   1348617.54        1.18
6                               FamilyGain   1846592.95        3.71
7                              Eldershield    520819.55        5.71

   Channel_sk Channel_code Married_Since House_tenure  NoOfHomes NumOfCars
0   Channel_6          DMI             2           21          2         2
1  Channel_24          DMI            15            8          1         2
2   Channel_5          DMI            10           18          3         1
3  Channel_22           SM             4           21          3         3
4  Channel_16         BANC             2            3          1         2
5   Channel_8         CELL            14           16          0         2
6  Channel_21         BANK            10           10          2         1
7  Channel_20          SUP             2            3          1         2

[8 rows x 28 columns]
   MARSTA_C Date_of_Birth         country  Age     Occupation Marital.Status  \
0         1    10/05/1969          Sweden   46     MANAGEMENT        Married
1         0    07/26/1972          Canada   43         OTHERS      Unmarried
2         0    08/05/1985          Russia   30  CIVIL SERVICE      Unmarried
3         0    12/10/1980           China   35             IT      Unmarried
4         1    12/12/1979      Kazakhstan   36     MANAGEMENT      Unmarried
5         0    10/27/1972       Indonesia   43         DOCTOR      Unmarried
6         1    06/24/1971       Indonesia   44         WORKER      Unmarried
7         1    03/06/1983           China   32         OTHERS        Married
8         0    06/23/1970  Czech Republic   45         OTHERS      Unmarried

   Annual.Income  Own.Home  Own.Car  Own.property  ... Premium_Amount  \
0      634668.78         2        1             2  ...     1298606.60
1     1812686.77         1        1             1  ...     5517797.85
2     1566549.64         2        1             2  ...     4559105.45
3      696245.15         1        2             1  ...     2539548.42
4     1324025.64         2        2             1  ...     4337399.11
5      801929.58         2        1             2  ...     2641898.18
6      401932.36         1        2             1  ...     3453549.28
7      627567.34         2        1             1  ...     1839349.40
8      498990.92         1        1             2  ...     1164180.65

                              Product_Name Claim_Amount NumOfClaims  \
0                           UnitGain Super   1924525.36        4.41
1                   Marine Cargo Insurance   2243649.44        7.41
2  Classic Annuity/Guaranteed Life Annuity    353072.93        5.13
3                                Unit Gain    988123.02        5.00
4                    Enhanced Incomeshield          NaN         NaN
5                              PrimeShield   1348617.54        1.18
6                               FamilyGain   1846592.95        3.71
7                              Eldershield    520819.55        5.71
8                                Protector     36614.02        0.52

   Channel_sk Channel_code Married_Since House_tenure  NoOfHomes NumOfCars
0   Channel_6          DMI             2           21          2         2
1  Channel_24          DMI            15            8          1         2
2   Channel_5          DMI            10           18          3         1
3  Channel_22           SM             4           21          3         3
4  Channel_16         BANC             2            3          1         2
5   Channel_8         CELL            14           16          0         2
6  Channel_21         BANK            10           10          2         1
7  Channel_20          SUP             2            3          1         2
8  Channel_25         BROK            17            1          0         1

[9 rows x 28 columns]